export const skeletonData: typeof kanto[0] = {
  name: "",
  badge: "",
  id: 0,
  img: "",
  type: "",
  leader: "",
  team: [],
};

export const kanto = [
  {
    name: "Pewter City",
    id: 1,
    img: "https://i.dstatic.com/images/trainers/league/brock.webp",
    type: "rock",
    badge: "Boulder Badge",
    leader: "Brock",
    team: [
      { id: 95, name: "Onix" },
      { id: 74, name: "Geodude" },
    ],
  },
  {
    name: "Cerulean City",
    id: 2,
    img: "https://i.dstatic.com/images/trainers/league/misty.webp",
    type: "water",
    badge: "Cascade Badge",
    leader: "Misty",
    team: [
      { id: 120, name: "Staryu" },
      { id: 121, name: "Starmie" },
    ],
  },
  {
    name: "Vermillion City",
    id: 3,
    img: "https://i.dstatic.com/images/trainers/league/lt.%20surge.webp",
    type: "electric",
    badge: "Thunder Badge",
    leader: "Lt. Surge",
    team: [
      { id: 100, name: "Voltorb" },
      { id: 25, name: "Pikachu" },
      { id: 26, name: "Raichu" },
    ],
  },
  {
    name: "Celadon City",
    id: 4,
    img: "https://i.dstatic.com/images/trainers/league/erika.webp",
    type: "grass",
    badge: "Rainbow Badge",
    leader: "Erika",
    team: [
      { id: 71, name: "Victreebel" },
      { id: 114, name: "Tangela" },
      { id: 45, name: "Vileplume" },
    ],
  },
  {
    name: "Fuchsia City",
    id: 5,
    img: "https://i.dstatic.com/images/trainers/league/janine.webp",
    type: "poison",
    badge: "Soul Badge",
    leader: "Janine",
    team: [
      { id: 109, name: "Koffing" },
      { id: 89, name: "Muk" },
      { id: 109, name: "Koffing" },
      { id: 110, name: "Weezing" },
    ],
  },
  {
    name: "Saffron City",
    id: 6,
    img: "https://i.dstatic.com/images/trainers/league/sabrina.webp",
    type: "psychic",
    badge: "Marsh Badge",
    leader: "Sabrina",
    team: [
      { id: 64, name: "Kadabra" },
      { id: 122, name: "Mr. Mime" },
      { id: 49, name: "Venomoth" },
      { id: 65, name: "Alakazam" },
    ],
  },
  {
    name: "Cinnabar Island",
    id: 7,
    img: "https://i.dstatic.com/images/trainers/league/blaine.webp",
    type: "fire",
    badge: "Volcano Badge",
    leader: "Blaine",
    team: [
      { id: 78, name: "Rapidash" },
      { id: 38, name: "Ninetales" },
      { id: 59, name: "Arcanine" },
      { id: 136, name: "Flareon" },
    ],
  },
  {
    name: "Viridian City",
    id: 8,
    img: "https://i.dstatic.com/images/trainers/league/giovanni.webp",
    type: "ground",
    badge: "Earth Badge",
    leader: "Giovanni",
    team: [
      { id: 50, name: "Diglett" },
      { id: 51, name: "Dugtrio" },
      { id: 53, name: "Persian" },
      { id: 24, name: "Arbok" },
      { id: 34, name: "Nidoking" },
      { id: 31, name: "Nidoqueen" },
    ],
  },
];
export const johto = [
  {
    name: "Violet City",
    id: 9,
    img: "https://i.dstatic.com/images/trainers/league/falkner.webp",
    type: "flying",
    badge: "Zephyr Badge",
    leader: "Falkner",
    team: [
      { id: 17, name: "Pidgeotto" },
      { id: 18, name: "Pidgeot" },
      { id: 16, name: "Pidgey" },
    ],
  },
  {
    name: "Azalea Town",
    id: 10,
    img: "https://i.dstatic.com/images/trainers/league/bugsy.webp",
    type: "bug",
    badge: "Hive Badge",
    leader: "Bugsy",
    team: [
      { id: 13, name: "Weedle" },
      { id: 14, name: "Kakuna" },
      { id: 15, name: "Beedrill" },
    ],
  },
  {
    name: "Goldenrod City",
    id: 11,
    img: "https://i.dstatic.com/images/trainers/league/whitney.webp",
    type: "normal",
    badge: "Plain Badge",
    leader: "Whitney",
    team: [
      { id: 35, name: "Clefairy" },
      { id: 241, name: "Miltank" },
    ],
  },
  {
    name: "Ecruteak City",
    id: 12,
    img: "https://i.dstatic.com/images/trainers/league/morty.webp",
    type: "ghost",
    badge: "Fog Badge",
    leader: "Morty",
    team: [
      { id: 92, name: "Gastly" },
      { id: 93, name: "Haunter" },
      { id: 94, name: "Gengar" },
      { id: 93, name: "Haunter" },
    ],
  },
  {
    name: "Cianwood City",
    id: 13,
    img: "https://i.dstatic.com/images/trainers/league/chuck.webp",
    type: "fighting",
    badge: "Storm Badge",
    leader: "Chuck",
    team: [
      { name: "Primeape", id: 57 },
      { name: "Poliwrath", id: 62 },
    ],
  },
  {
    name: "Olivine City",
    id: 14,
    img: "https://i.dstatic.com/images/trainers/league/jasmine.webp",
    type: "steel",
    badge: "Mineral Badge",
    leader: "Jasmine",
    team: [
      { id: 81, name: "Magnemite" },
      { id: 82, name: "Magneton" },
      { id: 208, name: "Steelix" },
    ],
  },
  {
    name: "Mahogany Town",
    id: 15,
    img: "https://i.dstatic.com/images/trainers/league/pryce.webp",
    type: "ice",
    badge: "Glacier Badge",
    leader: "Pryce",
    team: [
      { id: 86, name: "Seel" },
      { id: 87, name: "Dewgong" },
      { id: 221, name: "Piloswine" },
    ],
  },
  {
    name: "Blackthorn City",
    id: 16,
    img: "https://i.dstatic.com/images/trainers/league/clair.webp",
    type: "dragon",
    badge: "Rising Badge",
    leader: "Clair",
    team: [
      { id: 130, name: "Gyarados" },
      { id: 148, name: "Dragonair" },
      { id: 148, name: "Dragonair" },
      { id: 230, name: "Kingdra" },
    ],
  },
];
export const hoenn = [
  {
    name: "Rustboro City",
    id: 17,
    img: "https://i.dstatic.com/images/trainers/league/roxanne.webp",
    type: "rock",
    badge: "Stone Badge",
    leader: "Roxanne",
    team: [
      { id: 74, name: "Geodude" },
      { id: 299, name: "Nosepass" },
    ],
  },
  {
    name: "Dewford Town",
    id: 18,
    img: "https://i.dstatic.com/images/trainers/league/brawly.webp",
    type: "fighting",
    badge: "Knuckle Badge",
    leader: "Brawly",
    team: [
      { id: 66, name: "Machop" },
      { id: 296, name: "Makuhita" },
    ],
  },
  {
    name: "Mauville City",
    id: 19,
    img: "https://i.dstatic.com/images/trainers/league/wattson.webp",
    type: "electric",
    badge: "Dynamo Badge",
    leader: "Wattson",
    team: [
      { id: 81, name: "Magnemite" },
      { id: 100, name: "Voltorb" },
      { id: 82, name: "Magneton" },
    ],
  },
  {
    name: "Lavaridge Town",
    id: 20,
    img: "https://i.dstatic.com/images/trainers/league/flannery.webp",
    type: "fire",
    badge: "Heat Badge",
    leader: "Flannery",
    team: [
      { id: 218, name: "Slugma" },
      { id: 218, name: "Slugma" },
      { id: 324, name: "Torkoal" },
    ],
  },
  {
    name: "Petalburg City",
    id: 21,
    img: "https://i.dstatic.com/images/trainers/league/norman.webp",
    type: "normal",
    badge: "Balance Badge",
    leader: "Norman",
    team: [
      { id: 289, name: "Slaking" },
      { id: 288, name: "Vigoroth" },
      { id: 289, name: "Slaking" },
    ],
  },
  {
    name: "Fortree City",
    id: 22,
    img: "https://i.dstatic.com/images/trainers/league/winona.webp",
    type: "flying",
    badge: "Feather Badge",
    leader: "Winona",
    team: [
      { id: 277, name: "Swellow" },
      { id: 279, name: "Pelipper" },
      { id: 227, name: "Skarmory" },
      { id: 334, name: "Altaria" },
    ],
  },
  {
    name: "Mossdeep City",
    id: 23,
    img: "https://i.dstatic.com/images/trainers/league/tate%20and%20liza.webp",
    type: "psychic",
    badge: "Mind Badge",
    leader: "Tate and Liza",
    team: [
      { id: 337, name: "Lunatone" },
      { id: 338, name: "Solrock" },
    ],
  },
  {
    name: "Sootopolis City",
    id: 24,
    img: "https://i.dstatic.com/images/trainers/league/wallace.webp",
    type: "water",
    badge: "Rain Badge",
    leader: "Wallace",
    team: [
      { id: 370, name: "Luvdisc" },
      { id: 340, name: "Whiscash" },
      { id: 364, name: "Sealeo" },
      { id: 119, name: "Seaking" },
      { id: 350, name: "Milotic" },
    ],
  },
];
export const sinnoh = [
  {
    name: "Oreburgh City",
    id: 25,
    img: "https://i.dstatic.com/images/trainers/league/roark.webp",
    type: "rock",
    badge: "Coal Badge",
    leader: "Roark",
    team: [
      { id: 74, name: "Geodude" },
      { id: 95, name: "Onix" },
      { id: 408, name: "Cranidos" },
    ],
  },
  {
    name: "Eterna City",
    id: 26,
    img: "https://i.dstatic.com/images/trainers/league/gardenia.webp",
    type: "grass",
    badge: "Forest Badge",
    leader: "Gardenia",
    team: [
      { id: 420, name: "Cherubi" },
      { id: 387, name: "Turtwig" },
      { id: 407, name: "Roserade" },
    ],
  },
  {
    name: "Veilstone City",
    id: 27,
    img: "https://i.dstatic.com/images/trainers/league/maylene.webp",
    type: "fighting",
    badge: "Cobble Badge",
    leader: "Maylene",
    team: [
      { name: "Meditite", id: 307 },
      { name: "Machoke", id: 67 },
      { name: "Lucario", id: 448 },
    ],
  },
  {
    name: "Pastoria City",
    id: 28,
    img: "https://i.dstatic.com/images/trainers/league/wake.webp",
    type: "water",
    badge: "Fen Badge",
    leader: "Wake",
    team: [
      { name: "Gyarados", id: 130 },
      { name: "Quagsire", id: 195 },
      { name: "Floatzel", id: 419 },
    ],
  },
  {
    name: "Hearthome City",
    id: 29,
    img: "https://i.dstatic.com/images/trainers/league/fantina.webp",
    type: "ghost",
    badge: "Relic Badge",
    leader: "Fantina",
    team: [
      { name: "Drifblim", id: 426 },
      { name: "Gengar", id: 94 },
      { name: "Mismagius", id: 429 },
    ],
  },
  {
    name: "Canalave City",
    id: 30,
    img: "https://i.dstatic.com/images/trainers/league/byron.webp",
    type: "steel",
    badge: "Mine Badge",
    leader: "Byron",
    team: [
      { name: "Bronzor", id: 436 },
      { name: "Steelix", id: 208 },
      { name: "Bastiodon", id: 411 },
    ],
  },
  {
    name: "Snowpoint City",
    id: 31,
    img: "https://i.dstatic.com/images/trainers/league/candice.webp",
    type: "ice",
    badge: "Icicle Badge",
    leader: "Candice",
    team: [
      { name: "Snover", id: 361 },
      { name: "Sneasel", id: 215 },
      { name: "Medicham", id: 308 },
      { name: "Abomasnow", id: 460 },
    ],
  },
  {
    name: "Sunyshore City",
    id: 32,
    img: "https://i.dstatic.com/images/trainers/league/volkner.webp",
    type: "electric",
    badge: "Beacon Badge",
    leader: "Volkner",
    team: [
      { id: 26, name: "Raichu" },
      { id: 135, name: "Jolteon" },
      { id: 466, name: "Electivire" },
      { id: 405, name: "Luxray" },
    ],
  },
];
